name: Verify and deploy

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        # with:
        #   cache: 'npm'
      - name: Node modules
        run:
          cd app |
          npm i
      - name: Lint
        run:
          npm run lint
      - name: Compile and tests
        run:
          npm run test
  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: SAM build
        run: sam build --use-container
      - name: SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset